variable "RDS_ENGINE" {}
variable "RDS_ENGINE_VERSION" {}
variable "RDS_INSTANCE_CLASS" {}
variable "PRIVATE_SUBNET_ID" {}
variable "RGS_PORT" {}
variable "ALLOW_SG_CIDR" {}
variable "RDS_PG_FAMILY" {}
variable "PROJECT" {}
variable "ENV" {}
variable "VPC_ID" {}
